# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
#  config.vm.box = "ubuntubox"

  config.vm.define "pm" do |pm|

        pm.vm.box="ubuntubox"
	pm.vm.hostname="pm"
	# Create a private network, which allows host-only access to the machine
  	# using a specific IP.
  	pm.vm.network "private_network", ip: "192.168.33.10"


  end

  config.vm.define "agent1" do |agent1|

        agent1.vm.box="ubuntubox"
	agent1.vm.hostname="agent1"
        # Create a private network, which allows host-only access to the machine
        # using a specific IP.
        agent1.vm.network "private_network", ip: "192.168.33.15"

  end

end
